### ISSUE TITLE
Cyberpunk 2077 from GOG not detected

### ISSUE THREAD

**Issue by MrArdillo** [darklinkpower/PlaynitePlugin-NVIDIAGeForceNowEnabler#4]
The plugin not detect the game
![Sin título](https://user-images.githubusercontent.com/77178902/122085779-5880ec80-ce03-11eb-8991-afab45f9b9c4.png)

**Comment by darklinkpower** [comment]
Thanks for the heads up. I didn't realize there was not support for games from GOG in the extension, but added in https://github.com/darklinkpower/PlaynitePlugin-NVIDIAGeForceNowEnabler/commit/4945e30f2c363021cb39bea9b99fe4750a28169d

You can download the new version here 
https://github.com/darklinkpower/PlaynitePlugin-NVIDIAGeForceNowEnabler/releases/tag/1.6
